### ISSUE TITLE
Built wabs app doesn't name package.json file

### ISSUE THREAD

**Issue by dsw88** [byu-oit/wabs-starter#2]
I created a new app using wabs-starter, with the name "dsw88-test-wabs". I ran an npm install and then ran npm start to launch the app. I got this error:

```
> wabs-starter-app@1.0.0 start /Users/dsw88/projects/personal/wabs-test
> node $WABS_INSPECT index.js

ENV: development

Starting server app hot reload

Server listening on port 3000

Server app loading...

========================================
Server app loaded

Error: Multiple errors with properties in the object:
  Missing required value for property: consumerKey
  Missing required value for property: consumerSecret
  Missing required value for property: encryptSecret
    at Error (native)
    at Schema.validate (/Users/dsw88/projects/personal/wabs-test/node_modules/fully-typed/bin/schema.js:113:20)
    at Schema.normalize (/Users/dsw88/projects/personal/wabs-test/node_modules/fully-typed/bin/schema.js:97:10)
    at Middleware.getOptions.then.options (/Users/dsw88/projects/personal/wabs-test/node_modules/byu-wabs/bin/middleware.js:60:46)
```

I looked at the wabs middleware code and realized it was trying to load from the .wabs/config.json file using the name from my package.json, which was initialized to "wabs-starter-app".

I changed the name to my app name "dsw88-test-wabs", and the app started up successfully after doing that.

It would be great if the wabs-starter would set the name in package.json to be the name of the app we gave it in the wabs-starter configuration.

**Comment by Gi60s** [comment]
Sorry I never addressed this. Must have forgotten about it. There is a new version of WABS starter now that bypasses this error.
